#!/usr/bin/env python3
"""Build language ARB files from a translations table.

Each language has a dict mapping keys → translations. Keys we don't have a
translation for fall back to the English string from app_en.arb.
"""
import json
from pathlib import Path

EN_PATH = Path(__file__).parent / 'lib' / 'l10n' / 'app_en.arb'
OUT_DIR = Path(__file__).parent / 'lib' / 'l10n'

with open(EN_PATH) as f:
    en = json.load(f)

# Extract @-metadata so we can preserve placeholder definitions
metadata = {k: v for k, v in en.items() if k.startswith('@')}

# Translation tables — only keys we have confident translations for.
# Missing keys fall back to English string.

TRANSLATIONS = {
    'hi': {  # Hindi
        '@@locale': 'hi',
        'appName': 'फुटबॉल फैन हब 2026',
        'navHome': 'होम',
        'navFixtures': 'मैच',
        'navPredictor': 'भविष्यवाणी',
        'navTrivia': 'क्विज़',
        'navBracket': 'ब्रैकेट',
        'navStandings': 'अंक तालिका',
        'navFormat': 'प्रारूप',
        'navNews': 'समाचार',
        'actionSubmit': 'जमा करें',
        'actionCancel': 'रद्द करें',
        'actionShare': 'साझा करें',
        'actionSave': 'सहेजें',
        'actionDone': 'पूर्ण',
        'actionRetry': 'पुनः प्रयास',
        'actionRefresh': 'ताज़ा करें',
        'actionClose': 'बंद करें',
        'actionContinue': 'जारी रखें',
        'actionBack': 'वापस',
        'actionClear': 'साफ़ करें',
        'actionDelete': 'हटाएं',
        'actionEdit': 'संपादित करें',
        'actionUpdate': 'अपडेट',
        'actionPlay': 'चलाएं',
        'actionStart': 'शुरू करें',
        'actionFinish': 'समाप्त',
        'actionViewAll': 'सभी देखें',
        'actionMore': 'और',
        'statusLive': 'लाइव',
        'statusFinished': 'समाप्त',
        'statusFullTime': 'पूरा समय',
        'statusHalfTime': 'हाफ टाइम',
        'statusUpcoming': 'आगामी',
        'statusScheduled': 'निर्धारित',
        'statusToday': 'आज',
        'statusTomorrow': 'कल',
        'statusYesterday': 'बीता कल',
        'sectionTodayMatches': 'आज के मैच',
        'sectionFavoriteTeams': 'आपकी पसंदीदा टीमें',
        'sectionComingSoon': 'जल्द आ रहा है',
        'sectionUpcomingMatches': 'आगामी मैच',
        'sectionRecentForm': 'हालिया फॉर्म',
        'sectionStats': 'आँकड़े',
        'sectionSquad': 'दस्ता',
        'sectionClubInfo': 'क्लब जानकारी',
        'sectionAbout': 'के बारे में',
        'sectionGoals': 'गोल',
        'sectionMatchInfo': 'मैच की जानकारी',
        'sectionLineups': 'लाइनअप',
        'sectionH2H': 'आमने-सामने',
        'sectionStandings': 'अंक तालिका',
        'sectionSubstitutes': 'विकल्प',
        'sectionStartingXI': 'शुरुआती XI',
        'sectionBench': 'बेंच',
        'sectionAchievements': 'उपलब्धियाँ',
        'sectionStarPlayers': 'स्टार खिलाड़ी',
        'sectionCountryProfile': 'देश प्रोफ़ाइल',
        'sectionMomentum': 'गति',
        'sectionStatistics': 'सांख्यिकी',
        'sectionTimeline': 'मैच टाइमलाइन',
        'sectionLiveTicker': 'लाइव टिकर',
        'positionGoalkeepers': 'गोलकीपर',
        'positionDefenders': 'डिफेंडर',
        'positionMidfielders': 'मिडफील्डर',
        'positionForwards': 'फॉरवर्ड',
        'positionOther': 'अन्य',
        'tabSummary': 'सारांश',
        'tabLineups': 'लाइनअप',
        'tabStats': 'आँकड़े',
        'tabH2H': 'आमने-सामने',
        'tabStandings': 'तालिका',
        'tabPitch': 'मैदान',
        'tabList': 'सूची',
        'labelDate': 'तारीख़',
        'labelKickoff': 'किक-ऑफ',
        'labelCompetition': 'प्रतियोगिता',
        'labelStage': 'चरण',
        'labelGroup': 'समूह',
        'labelVenue': 'स्थल',
        'labelStatus': 'स्थिति',
        'labelFounded': 'स्थापना',
        'labelManager': 'प्रबंधक',
        'labelCoach': 'मुख्य कोच',
        'labelCountry': 'देश',
        'labelColours': 'रंग',
        'labelWebsite': 'वेबसाइट',
        'labelConfederation': 'महासंघ',
        'labelPlayed': 'खेले',
        'labelWins': 'जीत',
        'labelDraws': 'ड्रॉ',
        'labelLosses': 'हार',
        'labelGoalsFor': 'किए गोल',
        'labelGoalsAgainst': 'खाए गोल',
        'labelGoalDiff': 'गोल अंतर',
        'labelPoints': 'अंक',
        'labelPosition': 'पद',
        'labelNationality': 'राष्ट्रीयता',
        'labelAge': 'उम्र',
        'labelHeight': 'ऊँचाई',
        'labelWeight': 'वज़न',
        'labelShirt': 'जर्सी नं.',
        'labelTeam': 'टीम',
        'predictorTitle': 'भविष्यवाणी',
        'predictorYourPoints': 'आपके अंक',
        'predictorPredicted': 'भविष्यवाणी की',
        'predictorSettled': 'निपटाए गए',
        'predictorSubmit': 'भविष्यवाणी जमा करें',
        'predictorUpdate': 'भविष्यवाणी अपडेट करें',
        'predictorBeatMe': 'क्या आप मुझे हरा सकते हैं?',
        'predictorShareIntro': 'मेरी भविष्यवाणी',
        'triviaTitle': 'दैनिक फुटबॉल क्विज़',
        'triviaStart': 'क्विज़ शुरू करें',
        'triviaCorrect': 'सही',
        'triviaStreak': 'लकीर',
        'triviaBest': 'सर्वश्रेष्ठ',
        'triviaToday': 'आज',
        'triviaPerfect': 'परफेक्ट राउंड!',
        'triviaGreatJob': 'बहुत बढ़िया!',
        'triviaFinalScore': 'अंतिम स्कोर',
        'triviaTeamsToday': 'आज की टीमें',
        'triviaQuit': 'क्विज़ छोड़ें?',
        'triviaStay': 'जारी रखें',
        'triviaQuitAction': 'छोड़ें',
        'stageGroup': 'समूह',
        'stageRoundOf32': '32 का दौर',
        'stageRoundOf16': '16 का दौर',
        'stageQuarterFinal': 'क्वार्टर फाइनल',
        'stageSemiFinal': 'सेमी फाइनल',
        'stageFinal': 'फाइनल',
        'stageThirdPlace': 'तीसरा स्थान',
        'settingsTitle': 'सेटिंग्स',
        'settingsLanguage': 'भाषा',
        'settingsDarkMode': 'डार्क मोड',
        'settingsNotifications': 'सूचनाएं',
        'settingsSupport': 'सहायता',
        'settingsFeedback': 'प्रतिक्रिया',
        'settingsRateUs': 'हमें रेट करें',
        'settingsShareApp': 'ऐप साझा करें',
        'settingsPrivacyPolicy': 'गोपनीयता नीति',
        'settingsTerms': 'सेवा की शर्तें',
        'settingsRemoveAds': 'विज्ञापन हटाएं',
        'settingsRestorePurchases': 'खरीदारी पुनर्स्थापित करें',
        'settingsAdsRemoved': 'विज्ञापन हटाए गए',
        'settingsAdsRemovedThanks': 'समर्थन के लिए धन्यवाद!',
        'settingsRemoveAdsBuy': 'अभी खरीदें',
        'settingsLanguageDialogTitle': 'भाषा चुनें',
        'errorOffline': 'आप ऑफलाइन हैं',
        'errorLoad': 'डेटा लोड नहीं हो सका',
        'errorTryAgain': 'पुनः प्रयास करें',
        'errorNoMatches': 'कोई मैच नहीं',
        'favoriteAdd': 'पसंदीदा में जोड़ें',
        'favoriteRemove': 'पसंदीदा से हटाएं',
        'homeDidYouKnow': 'क्या आप जानते हैं?',
        'homeOnThisDay': 'आज के दिन',
        'newFanModeTitle': 'नया फैन मोड',
        'newFanModeCta': 'फुटबॉल में नए हैं?',
        'compareTitle': 'टीमों की तुलना',
        'qualSimTitle': 'योग्यता सिमुलेटर',
        'qualSimWin': 'जीत',
        'qualSimDraw': 'ड्रॉ',
        'qualSimLose': 'हार',
        'offlinePackTitle': 'ऑफलाइन मैच पैक',
        'bracketTitle': 'ब्रैकेट सिम्युलेटर',
        'bracketChampion': 'चैंपियन',
        'bracketRunnerUp': 'उपविजेता',
        'formatGuideTitle': 'प्रारूप गाइड',
        'newsTitle': 'फुटबॉल समाचार',
        'playerTitle': 'खिलाड़ी',
        'playerProfile': 'प्रोफ़ाइल',
        'playerBiography': 'जीवनी',
    },
    'ne': {  # Nepali — your local language
        '@@locale': 'ne',
        'appName': 'फुटबल फ्यान हब 2026',
        'navHome': 'गृह',
        'navFixtures': 'खेलहरू',
        'navPredictor': 'भविष्यवाणी',
        'navTrivia': 'क्विज',
        'navBracket': 'ब्र्याकेट',
        'navStandings': 'अङ्क तालिका',
        'navFormat': 'ढाँचा',
        'navNews': 'समाचार',
        'actionSubmit': 'पेश गर्नुहोस्',
        'actionCancel': 'रद्द',
        'actionShare': 'सेयर',
        'actionSave': 'सुरक्षित',
        'actionDone': 'सम्पन्न',
        'actionRetry': 'फेरि कोसिस',
        'actionRefresh': 'रिफ्रेस',
        'actionClose': 'बन्द',
        'actionContinue': 'जारी राख्नुहोस्',
        'actionBack': 'फर्कनुहोस्',
        'actionClear': 'खाली गर्नुहोस्',
        'actionDelete': 'मेटाउनुहोस्',
        'actionEdit': 'सम्पादन',
        'actionUpdate': 'अद्यावधिक',
        'actionPlay': 'चलाउनुहोस्',
        'actionStart': 'सुरु गर्नुहोस्',
        'actionFinish': 'समाप्त',
        'actionViewAll': 'सबै हेर्नुहोस्',
        'actionMore': 'थप',
        'statusLive': 'प्रत्यक्ष',
        'statusFinished': 'समाप्त',
        'statusFullTime': 'पूरा समय',
        'statusHalfTime': 'हाफ टाइम',
        'statusUpcoming': 'आगामी',
        'statusScheduled': 'तय गरिएको',
        'statusToday': 'आज',
        'statusTomorrow': 'भोलि',
        'statusYesterday': 'हिजो',
        'sectionTodayMatches': 'आजका खेलहरू',
        'sectionFavoriteTeams': 'तपाईंका मनपर्ने टोलीहरू',
        'sectionComingSoon': 'चाँडै आउँदै',
        'sectionUpcomingMatches': 'आगामी खेलहरू',
        'sectionRecentForm': 'हालैको फर्म',
        'sectionStats': 'तथ्याङ्क',
        'sectionSquad': 'दस्ता',
        'sectionClubInfo': 'क्लब जानकारी',
        'sectionAbout': 'बारेमा',
        'sectionGoals': 'गोलहरू',
        'sectionMatchInfo': 'खेल जानकारी',
        'sectionLineups': 'लाइनअप',
        'sectionH2H': 'आमनेसामने',
        'sectionStandings': 'अङ्क तालिका',
        'sectionSubstitutes': 'विकल्प',
        'sectionStartingXI': 'सुरुवाती ११',
        'sectionBench': 'बेन्च',
        'sectionAchievements': 'उपलब्धिहरू',
        'sectionStarPlayers': 'स्टार खेलाडीहरू',
        'sectionCountryProfile': 'देश प्रोफाइल',
        'sectionMomentum': 'गति',
        'sectionStatistics': 'तथ्याङ्क',
        'sectionTimeline': 'खेल टाइमलाइन',
        'sectionLiveTicker': 'प्रत्यक्ष टिकर',
        'positionGoalkeepers': 'गोलकीपर',
        'positionDefenders': 'डिफेन्डर',
        'positionMidfielders': 'मिडफिल्डर',
        'positionForwards': 'फरवार्ड',
        'positionOther': 'अन्य',
        'tabSummary': 'सारांश',
        'tabLineups': 'लाइनअप',
        'tabStats': 'तथ्याङ्क',
        'tabH2H': 'आमनेसामने',
        'tabStandings': 'तालिका',
        'tabPitch': 'मैदान',
        'tabList': 'सूची',
        'labelDate': 'मिति',
        'labelKickoff': 'किक-अफ',
        'labelCompetition': 'प्रतियोगिता',
        'labelStage': 'चरण',
        'labelGroup': 'समूह',
        'labelVenue': 'स्थल',
        'labelStatus': 'स्थिति',
        'labelFounded': 'स्थापना',
        'labelManager': 'प्रबन्धक',
        'labelCoach': 'मुख्य प्रशिक्षक',
        'labelCountry': 'देश',
        'labelColours': 'रङ',
        'labelWebsite': 'वेबसाइट',
        'labelConfederation': 'महासङ्घ',
        'labelPlayed': 'खेलिएको',
        'labelWins': 'जित',
        'labelDraws': 'बराबरी',
        'labelLosses': 'हार',
        'labelGoalsFor': 'गरिएका गोल',
        'labelGoalsAgainst': 'खाएका गोल',
        'labelGoalDiff': 'गोल अन्तर',
        'labelPoints': 'अङ्क',
        'labelPosition': 'पद',
        'labelNationality': 'राष्ट्रियता',
        'labelAge': 'उमेर',
        'labelHeight': 'उचाइ',
        'labelWeight': 'तौल',
        'labelShirt': 'जर्सी नं.',
        'labelTeam': 'टोली',
        'predictorTitle': 'भविष्यवाणी',
        'predictorYourPoints': 'तपाईंका अङ्क',
        'predictorPredicted': 'भविष्यवाणी गरियो',
        'predictorSettled': 'मिलाइयो',
        'predictorSubmit': 'भविष्यवाणी पेश गर्नुहोस्',
        'predictorUpdate': 'अद्यावधिक',
        'predictorBeatMe': 'के तपाईं मलाई जित्न सक्नुहुन्छ?',
        'predictorShareIntro': 'मेरो भविष्यवाणी',
        'triviaTitle': 'दैनिक फुटबल क्विज',
        'triviaStart': 'क्विज सुरु गर्नुहोस्',
        'triviaCorrect': 'सही',
        'triviaStreak': 'लगातार',
        'triviaBest': 'उत्कृष्ट',
        'triviaToday': 'आज',
        'triviaPerfect': 'पूर्ण राउन्ड!',
        'triviaGreatJob': 'राम्रो काम!',
        'triviaFinalScore': 'अन्तिम अङ्क',
        'triviaTeamsToday': 'आजका टोलीहरू',
        'triviaQuit': 'क्विज छाड्ने?',
        'triviaStay': 'रहनुहोस्',
        'triviaQuitAction': 'छाड्नुहोस्',
        'stageGroup': 'समूह',
        'stageRoundOf32': '३२ को राउन्ड',
        'stageRoundOf16': '१६ को राउन्ड',
        'stageQuarterFinal': 'क्वार्टरफाइनल',
        'stageSemiFinal': 'सेमिफाइनल',
        'stageFinal': 'फाइनल',
        'stageThirdPlace': 'तेस्रो स्थान',
        'settingsTitle': 'सेटिङ्ग्स',
        'settingsLanguage': 'भाषा',
        'settingsDarkMode': 'डार्क मोड',
        'settingsNotifications': 'सूचनाहरू',
        'settingsSupport': 'सहयोग',
        'settingsFeedback': 'प्रतिक्रिया',
        'settingsRateUs': 'हामीलाई मूल्याङ्कन गर्नुहोस्',
        'settingsShareApp': 'एप सेयर गर्नुहोस्',
        'settingsPrivacyPolicy': 'गोपनीयता नीति',
        'settingsTerms': 'सेवाका सर्तहरू',
        'settingsRemoveAds': 'विज्ञापन हटाउनुहोस्',
        'settingsRestorePurchases': 'खरिद पुनर्स्थापना',
        'settingsAdsRemoved': 'विज्ञापन हटाइयो',
        'settingsAdsRemovedThanks': 'सहयोगका लागि धन्यवाद!',
        'settingsRemoveAdsBuy': 'अहिले किन्नुहोस्',
        'settingsLanguageDialogTitle': 'भाषा छान्नुहोस्',
        'errorOffline': 'तपाईं अफलाइन हुनुहुन्छ',
        'errorLoad': 'डाटा लोड हुन सकेन',
        'errorTryAgain': 'फेरि कोसिस गर्नुहोस्',
        'errorNoMatches': 'कुनै खेल छैन',
        'favoriteAdd': 'मनपर्नेमा थप्नुहोस्',
        'favoriteRemove': 'मनपर्नेबाट हटाउनुहोस्',
        'homeDidYouKnow': 'के तपाईंलाई थाहा छ?',
        'homeOnThisDay': 'आजको दिनमा',
        'newFanModeTitle': 'नयाँ फ्यान मोड',
        'newFanModeCta': 'फुटबलमा नयाँ?',
        'compareTitle': 'टोलीहरू तुलना गर्नुहोस्',
        'qualSimTitle': 'योग्यता सिमुलेटर',
        'qualSimWin': 'जित',
        'qualSimDraw': 'बराबरी',
        'qualSimLose': 'हार',
        'offlinePackTitle': 'अफलाइन प्याक',
        'bracketTitle': 'ब्र्याकेट सिमुलेटर',
        'bracketChampion': 'च्याम्पियन',
        'bracketRunnerUp': 'उपविजेता',
        'formatGuideTitle': 'ढाँचा गाइड',
        'newsTitle': 'फुटबल समाचार',
        'playerTitle': 'खेलाडी',
        'playerProfile': 'प्रोफाइल',
        'playerBiography': 'जीवनी',
    },
    'es': {  # Spanish
        '@@locale': 'es',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'Inicio',
        'navFixtures': 'Partidos',
        'navPredictor': 'Pronóstico',
        'navTrivia': 'Trivia',
        'navBracket': 'Cuadro',
        'navStandings': 'Clasificación',
        'navFormat': 'Formato',
        'navNews': 'Noticias',
        'actionSubmit': 'Enviar',
        'actionCancel': 'Cancelar',
        'actionShare': 'Compartir',
        'actionSave': 'Guardar',
        'actionDone': 'Hecho',
        'actionRetry': 'Reintentar',
        'actionRefresh': 'Actualizar',
        'actionClose': 'Cerrar',
        'actionContinue': 'Continuar',
        'actionBack': 'Atrás',
        'actionClear': 'Borrar',
        'actionDelete': 'Eliminar',
        'actionEdit': 'Editar',
        'actionUpdate': 'Actualizar',
        'actionPlay': 'Jugar',
        'actionStart': 'Empezar',
        'actionFinish': 'Terminar',
        'actionViewAll': 'Ver todo',
        'actionMore': 'Más',
        'statusLive': 'EN VIVO',
        'statusFinished': 'FIN',
        'statusFullTime': 'Tiempo completo',
        'statusHalfTime': 'Medio tiempo',
        'statusUpcoming': 'Próximos',
        'statusScheduled': 'Programado',
        'statusToday': 'Hoy',
        'statusTomorrow': 'Mañana',
        'statusYesterday': 'Ayer',
        'sectionTodayMatches': 'Partidos de hoy',
        'sectionFavoriteTeams': 'Tus equipos favoritos',
        'sectionComingSoon': 'Próximamente',
        'sectionUpcomingMatches': 'Próximos partidos',
        'sectionRecentForm': 'Forma reciente',
        'sectionStats': 'Estadísticas',
        'sectionSquad': 'Plantilla',
        'sectionClubInfo': 'Info del club',
        'sectionAbout': 'Acerca de',
        'sectionGoals': 'Goles',
        'sectionMatchInfo': 'Información del partido',
        'sectionLineups': 'Alineaciones',
        'sectionH2H': 'Cara a cara',
        'sectionStandings': 'Clasificación',
        'sectionSubstitutes': 'Suplentes',
        'sectionStartingXI': 'XI titular',
        'sectionBench': 'Banca',
        'sectionAchievements': 'Logros',
        'sectionStarPlayers': 'Estrellas',
        'sectionCountryProfile': 'Perfil del país',
        'sectionMomentum': 'Momentum',
        'sectionStatistics': 'Estadísticas',
        'sectionTimeline': 'Cronología',
        'sectionLiveTicker': 'En vivo',
        'positionGoalkeepers': 'Porteros',
        'positionDefenders': 'Defensas',
        'positionMidfielders': 'Centrocampistas',
        'positionForwards': 'Delanteros',
        'positionOther': 'Otros',
        'tabSummary': 'Resumen',
        'tabLineups': 'Alineaciones',
        'tabStats': 'Stats',
        'tabH2H': 'H2H',
        'tabStandings': 'Tabla',
        'tabPitch': 'Campo',
        'tabList': 'Lista',
        'labelDate': 'Fecha',
        'labelKickoff': 'Inicio',
        'labelCompetition': 'Competición',
        'labelStage': 'Fase',
        'labelGroup': 'Grupo',
        'labelVenue': 'Sede',
        'labelStatus': 'Estado',
        'labelFounded': 'Fundado',
        'labelManager': 'Entrenador',
        'labelCoach': 'Seleccionador',
        'labelCountry': 'País',
        'labelColours': 'Colores',
        'labelWebsite': 'Web',
        'labelConfederation': 'Confederación',
        'labelPlayed': 'Jugados',
        'labelWins': 'Ganados',
        'labelDraws': 'Empates',
        'labelLosses': 'Perdidos',
        'labelGoalsFor': 'Goles a favor',
        'labelGoalsAgainst': 'Goles en contra',
        'labelGoalDiff': 'Diferencia',
        'labelPoints': 'Puntos',
        'labelPosition': 'Posición',
        'labelNationality': 'Nacionalidad',
        'labelAge': 'Edad',
        'labelHeight': 'Altura',
        'labelWeight': 'Peso',
        'labelShirt': 'Dorsal',
        'labelTeam': 'Equipo',
        'predictorTitle': 'Pronóstico',
        'predictorYourPoints': 'Tus puntos',
        'predictorPredicted': 'Pronosticados',
        'predictorSettled': 'Resueltos',
        'predictorSubmit': 'Enviar pronóstico',
        'predictorUpdate': 'Actualizar pronóstico',
        'predictorBeatMe': '¿Crees que puedes ganarme?',
        'predictorShareIntro': 'MI PRONÓSTICO',
        'triviaTitle': 'Trivia Diaria de Fútbol',
        'triviaStart': 'Empezar Quiz',
        'triviaCorrect': 'correctas',
        'triviaStreak': 'Racha',
        'triviaBest': 'Mejor',
        'triviaToday': 'Hoy',
        'triviaPerfect': '¡RONDA PERFECTA!',
        'triviaGreatJob': '¡Buen trabajo!',
        'triviaFinalScore': 'PUNTAJE FINAL',
        'triviaTeamsToday': 'Equipos de hoy',
        'triviaQuit': '¿Salir del quiz?',
        'triviaStay': 'Quedarme',
        'triviaQuitAction': 'Salir',
        'stageGroup': 'Grupos',
        'stageRoundOf32': 'Dieciseisavos',
        'stageRoundOf16': 'Octavos',
        'stageQuarterFinal': 'Cuartos',
        'stageSemiFinal': 'Semifinal',
        'stageFinal': 'Final',
        'stageThirdPlace': 'Tercer puesto',
        'settingsTitle': 'Ajustes',
        'settingsLanguage': 'Idioma',
        'settingsDarkMode': 'Modo oscuro',
        'settingsNotifications': 'Notificaciones',
        'settingsSupport': 'Soporte',
        'settingsFeedback': 'Comentarios',
        'settingsRateUs': 'Califícanos',
        'settingsShareApp': 'Compartir app',
        'settingsPrivacyPolicy': 'Privacidad',
        'settingsTerms': 'Términos',
        'settingsRemoveAds': 'Quitar anuncios',
        'settingsRestorePurchases': 'Restaurar compras',
        'settingsAdsRemoved': 'Anuncios eliminados',
        'settingsAdsRemovedThanks': '¡Gracias por apoyar!',
        'settingsRemoveAdsBuy': 'Comprar ahora',
        'settingsLanguageDialogTitle': 'Elegir idioma',
        'errorOffline': 'Estás sin conexión',
        'errorLoad': 'No se pudieron cargar los datos',
        'errorTryAgain': 'Intentar de nuevo',
        'errorNoMatches': 'Sin partidos',
        'favoriteAdd': 'Añadir a favoritos',
        'favoriteRemove': 'Quitar de favoritos',
        'homeDidYouKnow': '¿Sabías que?',
        'homeOnThisDay': 'Un día como hoy',
        'newFanModeTitle': 'Modo nuevo aficionado',
        'newFanModeCta': '¿Nuevo en el fútbol?',
        'compareTitle': 'Comparar equipos',
        'qualSimTitle': 'Simulador de clasificación',
        'qualSimWin': 'Ganar',
        'qualSimDraw': 'Empate',
        'qualSimLose': 'Perder',
        'offlinePackTitle': 'Paquete sin conexión',
        'bracketTitle': 'Simulador de cuadro',
        'bracketChampion': 'Campeón',
        'bracketRunnerUp': 'Subcampeón',
        'formatGuideTitle': 'Guía del formato',
        'newsTitle': 'Noticias de fútbol',
        'playerTitle': 'Jugador',
        'playerProfile': 'Perfil',
        'playerBiography': 'Biografía',
    },
    'fr': {  # French
        '@@locale': 'fr',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'Accueil',
        'navFixtures': 'Matchs',
        'navPredictor': 'Pronostics',
        'navTrivia': 'Quiz',
        'navBracket': 'Tableau',
        'navStandings': 'Classement',
        'navFormat': 'Format',
        'navNews': 'Actualités',
        'actionSubmit': 'Envoyer',
        'actionCancel': 'Annuler',
        'actionShare': 'Partager',
        'actionSave': 'Enregistrer',
        'actionDone': 'OK',
        'actionRetry': 'Réessayer',
        'actionRefresh': 'Actualiser',
        'actionClose': 'Fermer',
        'actionContinue': 'Continuer',
        'actionBack': 'Retour',
        'actionClear': 'Effacer',
        'actionDelete': 'Supprimer',
        'actionEdit': 'Modifier',
        'actionUpdate': 'Mettre à jour',
        'actionPlay': 'Jouer',
        'actionStart': 'Commencer',
        'actionFinish': 'Terminer',
        'actionViewAll': 'Voir tout',
        'actionMore': 'Plus',
        'statusLive': 'EN DIRECT',
        'statusFinished': 'TF',
        'statusFullTime': 'Temps réglementaire',
        'statusHalfTime': 'Mi-temps',
        'statusUpcoming': 'À venir',
        'statusScheduled': 'Programmé',
        'statusToday': 'Aujourd\'hui',
        'statusTomorrow': 'Demain',
        'statusYesterday': 'Hier',
        'sectionTodayMatches': 'Matchs du jour',
        'sectionFavoriteTeams': 'Vos équipes favorites',
        'sectionComingSoon': 'Bientôt',
        'sectionUpcomingMatches': 'Prochains matchs',
        'sectionRecentForm': 'Forme récente',
        'sectionStats': 'Stats',
        'sectionSquad': 'Effectif',
        'sectionClubInfo': 'Infos du club',
        'sectionAbout': 'À propos',
        'sectionGoals': 'Buts',
        'sectionMatchInfo': 'Infos du match',
        'sectionLineups': 'Compositions',
        'sectionH2H': 'Confrontations',
        'sectionStandings': 'Classement',
        'sectionSubstitutes': 'Remplaçants',
        'sectionStartingXI': 'XI de départ',
        'sectionBench': 'Banc',
        'sectionAchievements': 'Palmarès',
        'sectionStarPlayers': 'Stars',
        'sectionCountryProfile': 'Profil du pays',
        'sectionMomentum': 'Momentum',
        'sectionStatistics': 'Statistiques',
        'sectionTimeline': 'Chronologie',
        'sectionLiveTicker': 'En direct',
        'positionGoalkeepers': 'Gardiens',
        'positionDefenders': 'Défenseurs',
        'positionMidfielders': 'Milieux',
        'positionForwards': 'Attaquants',
        'positionOther': 'Autres',
        'tabSummary': 'Résumé',
        'tabLineups': 'Composition',
        'tabStats': 'Stats',
        'tabH2H': 'H2H',
        'tabStandings': 'Classement',
        'tabPitch': 'Terrain',
        'tabList': 'Liste',
        'labelDate': 'Date',
        'labelKickoff': 'Coup d\'envoi',
        'labelCompetition': 'Compétition',
        'labelStage': 'Phase',
        'labelGroup': 'Groupe',
        'labelVenue': 'Stade',
        'labelStatus': 'Statut',
        'labelFounded': 'Fondé',
        'labelManager': 'Entraîneur',
        'labelCoach': 'Sélectionneur',
        'labelCountry': 'Pays',
        'labelColours': 'Couleurs',
        'labelWebsite': 'Site web',
        'labelConfederation': 'Confédération',
        'labelPlayed': 'Joués',
        'labelWins': 'Gagnés',
        'labelDraws': 'Nuls',
        'labelLosses': 'Perdus',
        'labelGoalsFor': 'Buts pour',
        'labelGoalsAgainst': 'Buts contre',
        'labelGoalDiff': 'Différence',
        'labelPoints': 'Points',
        'labelPosition': 'Poste',
        'labelNationality': 'Nationalité',
        'labelAge': 'Âge',
        'labelHeight': 'Taille',
        'labelWeight': 'Poids',
        'labelShirt': 'Numéro',
        'labelTeam': 'Équipe',
        'predictorTitle': 'Pronostics',
        'predictorYourPoints': 'Vos points',
        'predictorSubmit': 'Envoyer le pronostic',
        'predictorBeatMe': 'Pensez-vous pouvoir me battre ?',
        'predictorShareIntro': 'MON PRONOSTIC',
        'triviaTitle': 'Quiz Football Quotidien',
        'triviaStart': 'Lancer le quiz',
        'triviaCorrect': 'correctes',
        'triviaStreak': 'Série',
        'triviaBest': 'Meilleur',
        'triviaToday': 'Aujourd\'hui',
        'triviaPerfect': 'PARTIE PARFAITE !',
        'triviaGreatJob': 'Bien joué !',
        'triviaFinalScore': 'SCORE FINAL',
        'triviaQuit': 'Quitter le quiz ?',
        'triviaStay': 'Rester',
        'triviaQuitAction': 'Quitter',
        'stageGroup': 'Groupes',
        'stageRoundOf32': 'Trente-deuxièmes',
        'stageRoundOf16': 'Huitièmes',
        'stageQuarterFinal': 'Quarts',
        'stageSemiFinal': 'Demi-finale',
        'stageFinal': 'Finale',
        'stageThirdPlace': 'Troisième place',
        'settingsTitle': 'Réglages',
        'settingsLanguage': 'Langue',
        'settingsDarkMode': 'Mode sombre',
        'settingsNotifications': 'Notifications',
        'settingsSupport': 'Support',
        'settingsFeedback': 'Commentaires',
        'settingsRateUs': 'Évaluer',
        'settingsShareApp': 'Partager l\'app',
        'settingsRemoveAds': 'Supprimer les pubs',
        'settingsAdsRemoved': 'Publicités supprimées',
        'settingsAdsRemovedThanks': 'Merci de votre soutien !',
        'settingsLanguageDialogTitle': 'Choisir la langue',
        'errorOffline': 'Vous êtes hors ligne',
        'errorLoad': 'Impossible de charger les données',
        'errorTryAgain': 'Réessayer',
        'errorNoMatches': 'Aucun match',
        'favoriteAdd': 'Ajouter aux favoris',
        'favoriteRemove': 'Retirer des favoris',
        'homeDidYouKnow': 'Le saviez-vous ?',
        'homeOnThisDay': 'Ce jour-là',
        'newFanModeTitle': 'Mode débutant',
        'newFanModeCta': 'Nouveau au football ?',
        'compareTitle': 'Comparer les équipes',
        'qualSimTitle': 'Simulateur de qualification',
        'qualSimWin': 'Gagner',
        'qualSimDraw': 'Nul',
        'qualSimLose': 'Perdre',
        'offlinePackTitle': 'Pack hors ligne',
        'bracketTitle': 'Simulateur de tableau',
        'bracketChampion': 'Champion',
        'bracketRunnerUp': 'Finaliste',
        'formatGuideTitle': 'Guide du format',
        'newsTitle': 'Actualités football',
        'playerTitle': 'Joueur',
        'playerProfile': 'Profil',
        'playerBiography': 'Biographie',
    },
    'de': {  # German
        '@@locale': 'de',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'Start',
        'navFixtures': 'Spielplan',
        'navPredictor': 'Tippspiel',
        'navTrivia': 'Quiz',
        'navBracket': 'Turnierbaum',
        'navStandings': 'Tabelle',
        'navFormat': 'Format',
        'navNews': 'News',
        'actionSubmit': 'Senden',
        'actionCancel': 'Abbrechen',
        'actionShare': 'Teilen',
        'actionSave': 'Speichern',
        'actionDone': 'Fertig',
        'actionRetry': 'Erneut',
        'actionRefresh': 'Aktualisieren',
        'actionClose': 'Schließen',
        'actionContinue': 'Weiter',
        'actionBack': 'Zurück',
        'actionClear': 'Löschen',
        'actionDelete': 'Entfernen',
        'actionEdit': 'Bearbeiten',
        'actionUpdate': 'Aktualisieren',
        'actionPlay': 'Spielen',
        'actionStart': 'Starten',
        'actionFinish': 'Beenden',
        'actionViewAll': 'Alle ansehen',
        'actionMore': 'Mehr',
        'statusLive': 'LIVE',
        'statusFinished': 'Schluss',
        'statusFullTime': 'Abpfiff',
        'statusHalfTime': 'Halbzeit',
        'statusUpcoming': 'Bevorstehend',
        'statusScheduled': 'Geplant',
        'statusToday': 'Heute',
        'statusTomorrow': 'Morgen',
        'statusYesterday': 'Gestern',
        'sectionTodayMatches': 'Spiele heute',
        'sectionFavoriteTeams': 'Ihre Lieblingsteams',
        'sectionComingSoon': 'Demnächst',
        'sectionUpcomingMatches': 'Kommende Spiele',
        'sectionRecentForm': 'Aktuelle Form',
        'sectionStats': 'Statistik',
        'sectionSquad': 'Kader',
        'sectionClubInfo': 'Vereinsinfo',
        'sectionAbout': 'Info',
        'sectionGoals': 'Tore',
        'sectionMatchInfo': 'Spielinfo',
        'sectionLineups': 'Aufstellungen',
        'sectionH2H': 'Direkter Vergleich',
        'sectionStandings': 'Tabelle',
        'sectionSubstitutes': 'Ersatz',
        'sectionStartingXI': 'Startelf',
        'sectionBench': 'Bank',
        'sectionAchievements': 'Erfolge',
        'sectionStarPlayers': 'Stars',
        'sectionCountryProfile': 'Länderprofil',
        'sectionMomentum': 'Momentum',
        'sectionStatistics': 'Statistik',
        'sectionTimeline': 'Spielverlauf',
        'sectionLiveTicker': 'Liveticker',
        'positionGoalkeepers': 'Torhüter',
        'positionDefenders': 'Verteidiger',
        'positionMidfielders': 'Mittelfeld',
        'positionForwards': 'Stürmer',
        'positionOther': 'Sonstige',
        'tabSummary': 'Zusammenfassung',
        'tabLineups': 'Aufstellung',
        'tabStats': 'Statistik',
        'tabH2H': 'H2H',
        'tabStandings': 'Tabelle',
        'tabPitch': 'Spielfeld',
        'tabList': 'Liste',
        'labelDate': 'Datum',
        'labelKickoff': 'Anstoß',
        'labelCompetition': 'Wettbewerb',
        'labelStage': 'Phase',
        'labelGroup': 'Gruppe',
        'labelVenue': 'Stadion',
        'labelStatus': 'Status',
        'labelFounded': 'Gegründet',
        'labelManager': 'Trainer',
        'labelCoach': 'Bundestrainer',
        'labelCountry': 'Land',
        'labelColours': 'Farben',
        'labelWebsite': 'Website',
        'labelConfederation': 'Verband',
        'labelPlayed': 'Spiele',
        'labelWins': 'Siege',
        'labelDraws': 'Unentsch.',
        'labelLosses': 'Niederlagen',
        'labelGoalsFor': 'Tore',
        'labelGoalsAgainst': 'Gegentore',
        'labelGoalDiff': 'Tordiff.',
        'labelPoints': 'Punkte',
        'labelPosition': 'Position',
        'labelNationality': 'Nationalität',
        'labelAge': 'Alter',
        'labelHeight': 'Größe',
        'labelWeight': 'Gewicht',
        'labelShirt': 'Trikot',
        'labelTeam': 'Team',
        'predictorTitle': 'Tippspiel',
        'predictorYourPoints': 'Ihre Punkte',
        'predictorSubmit': 'Tipp abgeben',
        'predictorBeatMe': 'Können Sie mich schlagen?',
        'predictorShareIntro': 'MEIN TIPP',
        'triviaTitle': 'Tägliches Fußball-Quiz',
        'triviaStart': 'Quiz starten',
        'triviaCorrect': 'richtig',
        'triviaStreak': 'Serie',
        'triviaBest': 'Bester',
        'triviaToday': 'Heute',
        'triviaPerfect': 'PERFEKTE RUNDE!',
        'triviaGreatJob': 'Super!',
        'triviaFinalScore': 'ENDPUNKTZAHL',
        'triviaQuit': 'Quiz beenden?',
        'triviaStay': 'Bleiben',
        'triviaQuitAction': 'Beenden',
        'stageGroup': 'Gruppen',
        'stageRoundOf32': 'Sechzehntelfinale',
        'stageRoundOf16': 'Achtelfinale',
        'stageQuarterFinal': 'Viertelfinale',
        'stageSemiFinal': 'Halbfinale',
        'stageFinal': 'Finale',
        'stageThirdPlace': 'Spiel um Platz 3',
        'settingsTitle': 'Einstellungen',
        'settingsLanguage': 'Sprache',
        'settingsDarkMode': 'Dunkler Modus',
        'settingsNotifications': 'Benachrichtigungen',
        'settingsSupport': 'Support',
        'settingsFeedback': 'Feedback',
        'settingsRateUs': 'Bewerten',
        'settingsShareApp': 'App teilen',
        'settingsRemoveAds': 'Werbung entfernen',
        'settingsAdsRemoved': 'Werbung entfernt',
        'settingsAdsRemovedThanks': 'Danke für Ihre Unterstützung!',
        'settingsLanguageDialogTitle': 'Sprache wählen',
        'errorOffline': 'Sie sind offline',
        'errorLoad': 'Daten konnten nicht geladen werden',
        'errorTryAgain': 'Erneut versuchen',
        'errorNoMatches': 'Keine Spiele',
        'favoriteAdd': 'Zu Favoriten',
        'favoriteRemove': 'Aus Favoriten entfernen',
        'homeDidYouKnow': 'Wussten Sie?',
        'homeOnThisDay': 'An diesem Tag',
        'newFanModeTitle': 'Anfängermodus',
        'newFanModeCta': 'Neu im Fußball?',
        'compareTitle': 'Teams vergleichen',
        'qualSimTitle': 'Qualifikations-Simulator',
        'qualSimWin': 'Sieg',
        'qualSimDraw': 'Unentschieden',
        'qualSimLose': 'Niederlage',
        'offlinePackTitle': 'Offline-Paket',
        'bracketTitle': 'Turnierbaum-Simulator',
        'bracketChampion': 'Champion',
        'bracketRunnerUp': 'Finalist',
        'formatGuideTitle': 'Format-Leitfaden',
        'newsTitle': 'Fußball-News',
        'playerTitle': 'Spieler',
        'playerProfile': 'Profil',
        'playerBiography': 'Biografie',
    },
    'ru': {  # Russian
        '@@locale': 'ru',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'Главная',
        'navFixtures': 'Матчи',
        'navPredictor': 'Прогнозы',
        'navTrivia': 'Викторина',
        'navBracket': 'Сетка',
        'navStandings': 'Таблица',
        'navFormat': 'Формат',
        'navNews': 'Новости',
        'actionSubmit': 'Отправить',
        'actionCancel': 'Отмена',
        'actionShare': 'Поделиться',
        'actionSave': 'Сохранить',
        'actionDone': 'Готово',
        'actionRetry': 'Повторить',
        'actionRefresh': 'Обновить',
        'actionClose': 'Закрыть',
        'actionContinue': 'Продолжить',
        'actionBack': 'Назад',
        'actionClear': 'Очистить',
        'actionDelete': 'Удалить',
        'actionEdit': 'Изменить',
        'actionUpdate': 'Обновить',
        'actionPlay': 'Играть',
        'actionStart': 'Начать',
        'actionFinish': 'Закончить',
        'actionViewAll': 'Все',
        'actionMore': 'Ещё',
        'statusLive': 'LIVE',
        'statusFinished': 'Завершён',
        'statusFullTime': 'Финальный свисток',
        'statusHalfTime': 'Перерыв',
        'statusUpcoming': 'Предстоящие',
        'statusScheduled': 'Запланирован',
        'statusToday': 'Сегодня',
        'statusTomorrow': 'Завтра',
        'statusYesterday': 'Вчера',
        'sectionTodayMatches': 'Матчи сегодня',
        'sectionFavoriteTeams': 'Любимые команды',
        'sectionComingSoon': 'Скоро',
        'sectionUpcomingMatches': 'Предстоящие матчи',
        'sectionRecentForm': 'Форма',
        'sectionStats': 'Статистика',
        'sectionSquad': 'Состав',
        'sectionClubInfo': 'О клубе',
        'sectionAbout': 'О команде',
        'sectionGoals': 'Голы',
        'sectionMatchInfo': 'О матче',
        'sectionLineups': 'Составы',
        'sectionH2H': 'Личные встречи',
        'sectionStandings': 'Таблица',
        'sectionSubstitutes': 'Замены',
        'sectionStartingXI': 'Стартовый состав',
        'sectionBench': 'Скамейка',
        'sectionAchievements': 'Достижения',
        'sectionStarPlayers': 'Звёзды',
        'sectionCountryProfile': 'Профиль страны',
        'sectionMomentum': 'Преимущество',
        'sectionStatistics': 'Статистика',
        'sectionTimeline': 'Хронология',
        'sectionLiveTicker': 'Прямая трансляция',
        'positionGoalkeepers': 'Вратари',
        'positionDefenders': 'Защитники',
        'positionMidfielders': 'Полузащитники',
        'positionForwards': 'Нападающие',
        'positionOther': 'Другие',
        'tabSummary': 'Обзор',
        'tabLineups': 'Составы',
        'tabStats': 'Статистика',
        'tabH2H': 'H2H',
        'tabStandings': 'Таблица',
        'tabPitch': 'Поле',
        'tabList': 'Список',
        'labelDate': 'Дата',
        'labelKickoff': 'Начало',
        'labelCompetition': 'Турнир',
        'labelStage': 'Стадия',
        'labelGroup': 'Группа',
        'labelVenue': 'Стадион',
        'labelStatus': 'Статус',
        'labelFounded': 'Основан',
        'labelManager': 'Тренер',
        'labelCoach': 'Главный тренер',
        'labelCountry': 'Страна',
        'labelColours': 'Цвета',
        'labelWebsite': 'Сайт',
        'labelConfederation': 'Конфедерация',
        'labelPlayed': 'Игры',
        'labelWins': 'Победы',
        'labelDraws': 'Ничьи',
        'labelLosses': 'Поражения',
        'labelGoalsFor': 'Забитые',
        'labelGoalsAgainst': 'Пропущенные',
        'labelGoalDiff': 'Разница',
        'labelPoints': 'Очки',
        'labelPosition': 'Позиция',
        'labelNationality': 'Гражданство',
        'labelAge': 'Возраст',
        'labelHeight': 'Рост',
        'labelWeight': 'Вес',
        'labelShirt': 'Номер',
        'labelTeam': 'Команда',
        'predictorTitle': 'Прогнозы',
        'predictorYourPoints': 'Ваши очки',
        'predictorSubmit': 'Отправить прогноз',
        'predictorBeatMe': 'Сможете меня обыграть?',
        'predictorShareIntro': 'МОЙ ПРОГНОЗ',
        'triviaTitle': 'Ежедневная футбольная викторина',
        'triviaStart': 'Начать',
        'triviaCorrect': 'правильно',
        'triviaStreak': 'Серия',
        'triviaBest': 'Лучший',
        'triviaToday': 'Сегодня',
        'triviaPerfect': 'ИДЕАЛЬНЫЙ РАУНД!',
        'triviaGreatJob': 'Отлично!',
        'triviaFinalScore': 'ИТОГ',
        'triviaQuit': 'Выйти из викторины?',
        'triviaStay': 'Остаться',
        'triviaQuitAction': 'Выйти',
        'stageGroup': 'Групповой этап',
        'stageRoundOf32': '1/16',
        'stageRoundOf16': '1/8',
        'stageQuarterFinal': 'Четвертьфинал',
        'stageSemiFinal': 'Полуфинал',
        'stageFinal': 'Финал',
        'stageThirdPlace': 'За 3-е место',
        'settingsTitle': 'Настройки',
        'settingsLanguage': 'Язык',
        'settingsDarkMode': 'Тёмная тема',
        'settingsNotifications': 'Уведомления',
        'settingsSupport': 'Поддержка',
        'settingsFeedback': 'Отзыв',
        'settingsRateUs': 'Оценить',
        'settingsShareApp': 'Поделиться приложением',
        'settingsRemoveAds': 'Убрать рекламу',
        'settingsAdsRemoved': 'Реклама убрана',
        'settingsAdsRemovedThanks': 'Спасибо за поддержку!',
        'settingsLanguageDialogTitle': 'Выберите язык',
        'errorOffline': 'Вы не в сети',
        'errorLoad': 'Не удалось загрузить данные',
        'errorTryAgain': 'Повторить',
        'errorNoMatches': 'Нет матчей',
        'favoriteAdd': 'В избранное',
        'favoriteRemove': 'Удалить из избранного',
        'homeDidYouKnow': 'А вы знали?',
        'homeOnThisDay': 'В этот день',
        'newFanModeTitle': 'Режим новичка',
        'newFanModeCta': 'Новичок в футболе?',
        'compareTitle': 'Сравнить команды',
        'qualSimTitle': 'Симулятор отбора',
        'qualSimWin': 'Победа',
        'qualSimDraw': 'Ничья',
        'qualSimLose': 'Поражение',
        'offlinePackTitle': 'Офлайн-пакет',
        'bracketTitle': 'Симулятор сетки',
        'bracketChampion': 'Чемпион',
        'bracketRunnerUp': 'Финалист',
        'formatGuideTitle': 'Гид по формату',
        'newsTitle': 'Футбольные новости',
        'playerTitle': 'Игрок',
        'playerProfile': 'Профиль',
        'playerBiography': 'Биография',
    },
    'zh': {  # Chinese Simplified
        '@@locale': 'zh',
        'appName': 'Football Fan Hub 2026',
        'navHome': '主页',
        'navFixtures': '赛程',
        'navPredictor': '预测',
        'navTrivia': '问答',
        'navBracket': '对阵图',
        'navStandings': '积分榜',
        'navFormat': '赛制',
        'navNews': '新闻',
        'actionSubmit': '提交',
        'actionCancel': '取消',
        'actionShare': '分享',
        'actionSave': '保存',
        'actionDone': '完成',
        'actionRetry': '重试',
        'actionRefresh': '刷新',
        'actionClose': '关闭',
        'actionContinue': '继续',
        'actionBack': '返回',
        'actionClear': '清除',
        'actionDelete': '删除',
        'actionEdit': '编辑',
        'actionUpdate': '更新',
        'actionPlay': '播放',
        'actionStart': '开始',
        'actionFinish': '结束',
        'actionViewAll': '查看全部',
        'actionMore': '更多',
        'statusLive': '直播',
        'statusFinished': '完场',
        'statusFullTime': '全场',
        'statusHalfTime': '中场',
        'statusUpcoming': '即将',
        'statusScheduled': '已安排',
        'statusToday': '今天',
        'statusTomorrow': '明天',
        'statusYesterday': '昨天',
        'sectionTodayMatches': '今日比赛',
        'sectionFavoriteTeams': '我的球队',
        'sectionComingSoon': '即将到来',
        'sectionUpcomingMatches': '即将比赛',
        'sectionRecentForm': '近期状态',
        'sectionStats': '统计',
        'sectionSquad': '阵容',
        'sectionClubInfo': '俱乐部信息',
        'sectionAbout': '关于',
        'sectionGoals': '进球',
        'sectionMatchInfo': '比赛信息',
        'sectionLineups': '首发阵容',
        'sectionH2H': '交锋记录',
        'sectionStandings': '积分榜',
        'sectionSubstitutes': '替补',
        'sectionStartingXI': '首发11人',
        'sectionBench': '替补席',
        'sectionAchievements': '荣誉',
        'sectionStarPlayers': '明星球员',
        'sectionCountryProfile': '国家概况',
        'sectionMomentum': '进攻势头',
        'sectionStatistics': '统计数据',
        'sectionTimeline': '比赛时间线',
        'sectionLiveTicker': '即时滚动',
        'positionGoalkeepers': '门将',
        'positionDefenders': '后卫',
        'positionMidfielders': '中场',
        'positionForwards': '前锋',
        'positionOther': '其他',
        'tabSummary': '概要',
        'tabLineups': '阵容',
        'tabStats': '统计',
        'tabH2H': '交锋',
        'tabStandings': '积分',
        'tabPitch': '球场',
        'tabList': '列表',
        'labelDate': '日期',
        'labelKickoff': '开球',
        'labelCompetition': '赛事',
        'labelStage': '阶段',
        'labelGroup': '小组',
        'labelVenue': '场馆',
        'labelStatus': '状态',
        'labelFounded': '成立',
        'labelManager': '主教练',
        'labelCoach': '国家队主帅',
        'labelCountry': '国家',
        'labelColours': '颜色',
        'labelWebsite': '网站',
        'labelConfederation': '足联',
        'labelPlayed': '比赛',
        'labelWins': '胜',
        'labelDraws': '平',
        'labelLosses': '负',
        'labelGoalsFor': '进球',
        'labelGoalsAgainst': '失球',
        'labelGoalDiff': '净胜球',
        'labelPoints': '积分',
        'labelPosition': '位置',
        'labelNationality': '国籍',
        'labelAge': '年龄',
        'labelHeight': '身高',
        'labelWeight': '体重',
        'labelShirt': '球衣号',
        'labelTeam': '球队',
        'predictorTitle': '比分预测',
        'predictorYourPoints': '你的得分',
        'predictorSubmit': '提交预测',
        'predictorBeatMe': '你能赢过我吗?',
        'predictorShareIntro': '我的预测',
        'triviaTitle': '每日足球问答',
        'triviaStart': '开始问答',
        'triviaCorrect': '正确',
        'triviaStreak': '连续',
        'triviaBest': '最佳',
        'triviaToday': '今天',
        'triviaPerfect': '完美一轮!',
        'triviaGreatJob': '干得好!',
        'triviaFinalScore': '最终得分',
        'triviaQuit': '退出问答?',
        'triviaStay': '继续',
        'triviaQuitAction': '退出',
        'stageGroup': '小组赛',
        'stageRoundOf32': '32强',
        'stageRoundOf16': '16强',
        'stageQuarterFinal': '四分之一决赛',
        'stageSemiFinal': '半决赛',
        'stageFinal': '决赛',
        'stageThirdPlace': '季军赛',
        'settingsTitle': '设置',
        'settingsLanguage': '语言',
        'settingsDarkMode': '深色模式',
        'settingsNotifications': '通知',
        'settingsSupport': '支持',
        'settingsFeedback': '反馈',
        'settingsRateUs': '评价',
        'settingsShareApp': '分享应用',
        'settingsRemoveAds': '移除广告',
        'settingsAdsRemoved': '广告已移除',
        'settingsAdsRemovedThanks': '感谢您的支持!',
        'settingsLanguageDialogTitle': '选择语言',
        'errorOffline': '你处于离线状态',
        'errorLoad': '无法加载数据',
        'errorTryAgain': '再试一次',
        'errorNoMatches': '没有比赛',
        'favoriteAdd': '添加到收藏',
        'favoriteRemove': '从收藏中移除',
        'homeDidYouKnow': '你知道吗?',
        'homeOnThisDay': '历史上的今天',
        'newFanModeTitle': '新球迷模式',
        'newFanModeCta': '足球新手?',
        'compareTitle': '球队对比',
        'qualSimTitle': '出线模拟器',
        'qualSimWin': '赢',
        'qualSimDraw': '平',
        'qualSimLose': '输',
        'offlinePackTitle': '离线包',
        'bracketTitle': '对阵图模拟器',
        'bracketChampion': '冠军',
        'bracketRunnerUp': '亚军',
        'formatGuideTitle': '赛制指南',
        'newsTitle': '足球新闻',
        'playerTitle': '球员',
        'playerProfile': '资料',
        'playerBiography': '简介',
    },
    'ja': {  # Japanese
        '@@locale': 'ja',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'ホーム',
        'navFixtures': '日程',
        'navPredictor': '予想',
        'navTrivia': 'クイズ',
        'navBracket': 'トーナメント',
        'navStandings': '順位',
        'navFormat': 'フォーマット',
        'navNews': 'ニュース',
        'actionSubmit': '送信',
        'actionCancel': 'キャンセル',
        'actionShare': '共有',
        'actionSave': '保存',
        'actionDone': '完了',
        'actionRetry': '再試行',
        'actionRefresh': '更新',
        'actionClose': '閉じる',
        'actionContinue': '続ける',
        'actionBack': '戻る',
        'actionClear': 'クリア',
        'actionDelete': '削除',
        'actionEdit': '編集',
        'actionUpdate': '更新',
        'actionPlay': '再生',
        'actionStart': '開始',
        'actionFinish': '終了',
        'actionViewAll': 'すべて表示',
        'actionMore': 'もっと',
        'statusLive': 'ライブ',
        'statusFinished': '試合終了',
        'statusFullTime': 'フルタイム',
        'statusHalfTime': 'ハーフタイム',
        'statusUpcoming': '今後',
        'statusScheduled': '予定',
        'statusToday': '今日',
        'statusTomorrow': '明日',
        'statusYesterday': '昨日',
        'sectionTodayMatches': '今日の試合',
        'sectionFavoriteTeams': 'お気に入りチーム',
        'sectionComingSoon': 'まもなく',
        'sectionUpcomingMatches': '今後の試合',
        'sectionRecentForm': '最近の調子',
        'sectionStats': '統計',
        'sectionSquad': 'スカッド',
        'sectionClubInfo': 'クラブ情報',
        'sectionAbout': '概要',
        'sectionGoals': 'ゴール',
        'sectionMatchInfo': '試合情報',
        'sectionLineups': 'スターティングメンバー',
        'sectionH2H': '対戦成績',
        'sectionStandings': '順位表',
        'sectionSubstitutes': '控え',
        'sectionStartingXI': '先発XI',
        'sectionBench': 'ベンチ',
        'sectionAchievements': '実績',
        'sectionStarPlayers': 'スター選手',
        'sectionCountryProfile': '国プロフィール',
        'sectionMomentum': '勢い',
        'sectionStatistics': '統計',
        'sectionTimeline': 'タイムライン',
        'sectionLiveTicker': 'ライブティッカー',
        'positionGoalkeepers': 'ゴールキーパー',
        'positionDefenders': 'ディフェンダー',
        'positionMidfielders': 'ミッドフィルダー',
        'positionForwards': 'フォワード',
        'positionOther': 'その他',
        'tabSummary': '概要',
        'tabLineups': 'メンバー',
        'tabStats': '統計',
        'tabH2H': 'H2H',
        'tabStandings': '順位',
        'tabPitch': 'ピッチ',
        'tabList': 'リスト',
        'labelDate': '日付',
        'labelKickoff': 'キックオフ',
        'labelCompetition': '大会',
        'labelStage': 'ステージ',
        'labelGroup': 'グループ',
        'labelVenue': '会場',
        'labelStatus': 'ステータス',
        'labelFounded': '創設',
        'labelManager': '監督',
        'labelCoach': '代表監督',
        'labelCountry': '国',
        'labelColours': 'カラー',
        'labelWebsite': 'ウェブサイト',
        'labelConfederation': '連盟',
        'labelPlayed': '試合数',
        'labelWins': '勝',
        'labelDraws': '分',
        'labelLosses': '敗',
        'labelGoalsFor': '得点',
        'labelGoalsAgainst': '失点',
        'labelGoalDiff': '得失点差',
        'labelPoints': '勝点',
        'labelPosition': 'ポジション',
        'labelNationality': '国籍',
        'labelAge': '年齢',
        'labelHeight': '身長',
        'labelWeight': '体重',
        'labelShirt': '背番号',
        'labelTeam': 'チーム',
        'predictorTitle': '予想',
        'predictorYourPoints': 'あなたのポイント',
        'predictorSubmit': '予想を送信',
        'predictorBeatMe': '私に勝てる?',
        'predictorShareIntro': '私の予想',
        'triviaTitle': '毎日のサッカークイズ',
        'triviaStart': 'クイズを始める',
        'triviaCorrect': '正解',
        'triviaStreak': '連続',
        'triviaBest': 'ベスト',
        'triviaToday': '今日',
        'triviaPerfect': 'パーフェクト!',
        'triviaGreatJob': 'よくできました!',
        'triviaFinalScore': '最終スコア',
        'triviaQuit': 'クイズを終了?',
        'triviaStay': '続ける',
        'triviaQuitAction': '終了',
        'stageGroup': 'グループステージ',
        'stageRoundOf32': 'ラウンド32',
        'stageRoundOf16': 'ラウンド16',
        'stageQuarterFinal': '準々決勝',
        'stageSemiFinal': '準決勝',
        'stageFinal': '決勝',
        'stageThirdPlace': '3位決定戦',
        'settingsTitle': '設定',
        'settingsLanguage': '言語',
        'settingsDarkMode': 'ダークモード',
        'settingsNotifications': '通知',
        'settingsSupport': 'サポート',
        'settingsFeedback': 'フィードバック',
        'settingsRateUs': '評価する',
        'settingsShareApp': 'アプリを共有',
        'settingsRemoveAds': '広告削除',
        'settingsAdsRemoved': '広告削除済み',
        'settingsAdsRemovedThanks': 'ご支援ありがとうございます!',
        'settingsLanguageDialogTitle': '言語を選択',
        'errorOffline': 'オフラインです',
        'errorLoad': 'データを読み込めません',
        'errorTryAgain': '再試行',
        'errorNoMatches': '試合なし',
        'favoriteAdd': 'お気に入りに追加',
        'favoriteRemove': 'お気に入りから削除',
        'homeDidYouKnow': '知ってた?',
        'homeOnThisDay': 'この日',
        'newFanModeTitle': '初心者モード',
        'newFanModeCta': 'サッカー初心者?',
        'compareTitle': 'チーム比較',
        'qualSimTitle': '予選シミュレーター',
        'qualSimWin': '勝',
        'qualSimDraw': '分',
        'qualSimLose': '負',
        'offlinePackTitle': 'オフラインパック',
        'bracketTitle': 'トーナメントシミュレーター',
        'bracketChampion': 'チャンピオン',
        'bracketRunnerUp': '準優勝',
        'formatGuideTitle': 'フォーマットガイド',
        'newsTitle': 'サッカーニュース',
        'playerTitle': '選手',
        'playerProfile': 'プロフィール',
        'playerBiography': '経歴',
    },
    'ko': {  # Korean
        '@@locale': 'ko',
        'appName': 'Football Fan Hub 2026',
        'navHome': '홈',
        'navFixtures': '경기',
        'navPredictor': '예측',
        'navTrivia': '퀴즈',
        'navBracket': '대진표',
        'navStandings': '순위',
        'navFormat': '방식',
        'navNews': '뉴스',
        'actionSubmit': '제출',
        'actionCancel': '취소',
        'actionShare': '공유',
        'actionSave': '저장',
        'actionDone': '완료',
        'actionRetry': '재시도',
        'actionRefresh': '새로고침',
        'actionClose': '닫기',
        'actionContinue': '계속',
        'actionBack': '뒤로',
        'actionClear': '지우기',
        'actionDelete': '삭제',
        'actionEdit': '편집',
        'actionUpdate': '업데이트',
        'actionPlay': '재생',
        'actionStart': '시작',
        'actionFinish': '종료',
        'actionViewAll': '전체 보기',
        'actionMore': '더보기',
        'statusLive': '라이브',
        'statusFinished': '경기 종료',
        'statusFullTime': '풀타임',
        'statusHalfTime': '하프타임',
        'statusUpcoming': '예정',
        'statusScheduled': '예약됨',
        'statusToday': '오늘',
        'statusTomorrow': '내일',
        'statusYesterday': '어제',
        'sectionTodayMatches': '오늘 경기',
        'sectionFavoriteTeams': '내 즐겨찾는 팀',
        'sectionComingSoon': '곧 시작',
        'sectionUpcomingMatches': '예정된 경기',
        'sectionRecentForm': '최근 폼',
        'sectionStats': '통계',
        'sectionSquad': '선수단',
        'sectionClubInfo': '구단 정보',
        'sectionAbout': '소개',
        'sectionGoals': '골',
        'sectionMatchInfo': '경기 정보',
        'sectionLineups': '라인업',
        'sectionH2H': '맞대결',
        'sectionStandings': '순위표',
        'sectionSubstitutes': '교체 선수',
        'sectionStartingXI': '선발 11명',
        'sectionBench': '벤치',
        'sectionAchievements': '업적',
        'sectionStarPlayers': '스타 선수',
        'sectionCountryProfile': '국가 프로필',
        'sectionMomentum': '기세',
        'sectionStatistics': '통계',
        'sectionTimeline': '타임라인',
        'sectionLiveTicker': '라이브 티커',
        'positionGoalkeepers': '골키퍼',
        'positionDefenders': '수비수',
        'positionMidfielders': '미드필더',
        'positionForwards': '공격수',
        'positionOther': '기타',
        'tabSummary': '요약',
        'tabLineups': '라인업',
        'tabStats': '통계',
        'tabH2H': '맞대결',
        'tabStandings': '순위',
        'tabPitch': '경기장',
        'tabList': '목록',
        'labelDate': '날짜',
        'labelKickoff': '킥오프',
        'labelCompetition': '대회',
        'labelStage': '단계',
        'labelGroup': '조',
        'labelVenue': '경기장',
        'labelStatus': '상태',
        'labelFounded': '창단',
        'labelManager': '감독',
        'labelCoach': '국가대표 감독',
        'labelCountry': '국가',
        'labelColours': '색상',
        'labelWebsite': '웹사이트',
        'labelConfederation': '연맹',
        'labelPlayed': '경기',
        'labelWins': '승',
        'labelDraws': '무',
        'labelLosses': '패',
        'labelGoalsFor': '득점',
        'labelGoalsAgainst': '실점',
        'labelGoalDiff': '득실차',
        'labelPoints': '승점',
        'labelPosition': '포지션',
        'labelNationality': '국적',
        'labelAge': '나이',
        'labelHeight': '신장',
        'labelWeight': '체중',
        'labelShirt': '등번호',
        'labelTeam': '팀',
        'predictorTitle': '예측',
        'predictorYourPoints': '내 포인트',
        'predictorSubmit': '예측 제출',
        'predictorBeatMe': '날 이길 수 있어?',
        'predictorShareIntro': '내 예측',
        'triviaTitle': '오늘의 축구 퀴즈',
        'triviaStart': '퀴즈 시작',
        'triviaCorrect': '정답',
        'triviaStreak': '연속',
        'triviaBest': '최고',
        'triviaToday': '오늘',
        'triviaPerfect': '완벽한 한판!',
        'triviaGreatJob': '잘했어요!',
        'triviaFinalScore': '최종 점수',
        'triviaQuit': '퀴즈를 종료할까요?',
        'triviaStay': '계속하기',
        'triviaQuitAction': '종료',
        'stageGroup': '조별리그',
        'stageRoundOf32': '32강',
        'stageRoundOf16': '16강',
        'stageQuarterFinal': '8강',
        'stageSemiFinal': '준결승',
        'stageFinal': '결승',
        'stageThirdPlace': '3·4위전',
        'settingsTitle': '설정',
        'settingsLanguage': '언어',
        'settingsDarkMode': '다크 모드',
        'settingsNotifications': '알림',
        'settingsSupport': '지원',
        'settingsFeedback': '의견 보내기',
        'settingsRateUs': '평가하기',
        'settingsShareApp': '앱 공유',
        'settingsRemoveAds': '광고 제거',
        'settingsAdsRemoved': '광고 제거됨',
        'settingsAdsRemovedThanks': '지원해 주셔서 감사합니다!',
        'settingsLanguageDialogTitle': '언어 선택',
        'errorOffline': '오프라인 상태입니다',
        'errorLoad': '데이터를 불러올 수 없습니다',
        'errorTryAgain': '다시 시도',
        'errorNoMatches': '경기 없음',
        'favoriteAdd': '즐겨찾기 추가',
        'favoriteRemove': '즐겨찾기 해제',
        'homeDidYouKnow': '알고 있나요?',
        'homeOnThisDay': '오늘의 역사',
        'newFanModeTitle': '입문자 모드',
        'newFanModeCta': '축구가 처음인가요?',
        'compareTitle': '팀 비교',
        'qualSimTitle': '본선 진출 시뮬레이터',
        'qualSimWin': '승',
        'qualSimDraw': '무',
        'qualSimLose': '패',
        'offlinePackTitle': '오프라인 팩',
        'bracketTitle': '대진표 시뮬레이터',
        'bracketChampion': '우승',
        'bracketRunnerUp': '준우승',
        'formatGuideTitle': '대회 방식 안내',
        'newsTitle': '축구 뉴스',
        'playerTitle': '선수',
        'playerProfile': '프로필',
        'playerBiography': '약력',
    },
    'pt': {  # Portuguese (BR-friendly)
        '@@locale': 'pt',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'Início',
        'navFixtures': 'Jogos',
        'navPredictor': 'Palpites',
        'navTrivia': 'Quiz',
        'navBracket': 'Chaveamento',
        'navStandings': 'Classificação',
        'navFormat': 'Formato',
        'navNews': 'Notícias',
        'actionSubmit': 'Enviar',
        'actionCancel': 'Cancelar',
        'actionShare': 'Compartilhar',
        'actionSave': 'Salvar',
        'actionDone': 'Pronto',
        'actionRetry': 'Tentar novamente',
        'actionRefresh': 'Atualizar',
        'actionClose': 'Fechar',
        'actionContinue': 'Continuar',
        'actionBack': 'Voltar',
        'actionClear': 'Limpar',
        'actionDelete': 'Excluir',
        'actionEdit': 'Editar',
        'actionUpdate': 'Atualizar',
        'actionPlay': 'Reproduzir',
        'actionStart': 'Iniciar',
        'actionFinish': 'Encerrar',
        'actionViewAll': 'Ver tudo',
        'actionMore': 'Mais',
        'statusLive': 'AO VIVO',
        'statusFinished': 'Encerrado',
        'statusFullTime': 'Tempo final',
        'statusHalfTime': 'Intervalo',
        'statusUpcoming': 'Próximos',
        'statusScheduled': 'Marcado',
        'statusToday': 'Hoje',
        'statusTomorrow': 'Amanhã',
        'statusYesterday': 'Ontem',
        'sectionTodayMatches': 'Jogos de hoje',
        'sectionFavoriteTeams': 'Times favoritos',
        'sectionComingSoon': 'Em breve',
        'sectionUpcomingMatches': 'Próximos jogos',
        'sectionRecentForm': 'Forma recente',
        'sectionStats': 'Estatísticas',
        'sectionSquad': 'Elenco',
        'sectionClubInfo': 'Sobre o clube',
        'sectionAbout': 'Sobre',
        'sectionGoals': 'Gols',
        'sectionMatchInfo': 'Sobre o jogo',
        'sectionLineups': 'Escalações',
        'sectionH2H': 'Confronto direto',
        'sectionStandings': 'Classificação',
        'sectionSubstitutes': 'Reservas',
        'sectionStartingXI': 'XI titular',
        'sectionBench': 'Banco',
        'sectionAchievements': 'Conquistas',
        'sectionStarPlayers': 'Estrelas',
        'sectionCountryProfile': 'Perfil do país',
        'sectionMomentum': 'Momento',
        'sectionStatistics': 'Estatísticas',
        'sectionTimeline': 'Linha do tempo',
        'sectionLiveTicker': 'Lances ao vivo',
        'positionGoalkeepers': 'Goleiros',
        'positionDefenders': 'Defensores',
        'positionMidfielders': 'Meio-campistas',
        'positionForwards': 'Atacantes',
        'positionOther': 'Outros',
        'tabSummary': 'Resumo',
        'tabLineups': 'Escalação',
        'tabStats': 'Stats',
        'tabH2H': 'H2H',
        'tabStandings': 'Tabela',
        'tabPitch': 'Campo',
        'tabList': 'Lista',
        'labelDate': 'Data',
        'labelKickoff': 'Início',
        'labelCompetition': 'Competição',
        'labelStage': 'Fase',
        'labelGroup': 'Grupo',
        'labelVenue': 'Local',
        'labelStatus': 'Status',
        'labelFounded': 'Fundado',
        'labelManager': 'Técnico',
        'labelCoach': 'Treinador',
        'labelCountry': 'País',
        'labelColours': 'Cores',
        'labelWebsite': 'Site',
        'labelConfederation': 'Confederação',
        'labelPlayed': 'Jogos',
        'labelWins': 'V',
        'labelDraws': 'E',
        'labelLosses': 'D',
        'labelGoalsFor': 'GP',
        'labelGoalsAgainst': 'GC',
        'labelGoalDiff': 'SG',
        'labelPoints': 'Pts',
        'labelPosition': 'Posição',
        'labelNationality': 'Nacionalidade',
        'labelAge': 'Idade',
        'labelHeight': 'Altura',
        'labelWeight': 'Peso',
        'labelShirt': 'Camisa',
        'labelTeam': 'Time',
        'predictorTitle': 'Palpites',
        'predictorYourPoints': 'Seus pontos',
        'predictorSubmit': 'Enviar palpite',
        'predictorBeatMe': 'Acha que pode me vencer?',
        'predictorShareIntro': 'MEU PALPITE',
        'triviaTitle': 'Quiz Diário de Futebol',
        'triviaStart': 'Iniciar Quiz',
        'triviaCorrect': 'corretas',
        'triviaStreak': 'Sequência',
        'triviaBest': 'Recorde',
        'triviaToday': 'Hoje',
        'triviaPerfect': 'RODADA PERFEITA!',
        'triviaGreatJob': 'Bom trabalho!',
        'triviaFinalScore': 'PONTUAÇÃO FINAL',
        'triviaQuit': 'Sair do quiz?',
        'triviaStay': 'Continuar',
        'triviaQuitAction': 'Sair',
        'stageGroup': 'Grupos',
        'stageRoundOf32': 'Trigésima-segunda',
        'stageRoundOf16': 'Oitavas',
        'stageQuarterFinal': 'Quartas',
        'stageSemiFinal': 'Semifinal',
        'stageFinal': 'Final',
        'stageThirdPlace': 'Disputa de 3º lugar',
        'settingsTitle': 'Configurações',
        'settingsLanguage': 'Idioma',
        'settingsDarkMode': 'Modo escuro',
        'settingsNotifications': 'Notificações',
        'settingsSupport': 'Suporte',
        'settingsFeedback': 'Comentários',
        'settingsRateUs': 'Avalie-nos',
        'settingsShareApp': 'Compartilhar app',
        'settingsRemoveAds': 'Remover anúncios',
        'settingsAdsRemoved': 'Anúncios removidos',
        'settingsAdsRemovedThanks': 'Obrigado pelo apoio!',
        'settingsLanguageDialogTitle': 'Escolher idioma',
        'errorOffline': 'Você está offline',
        'errorLoad': 'Não foi possível carregar os dados',
        'errorTryAgain': 'Tentar novamente',
        'errorNoMatches': 'Nenhum jogo',
        'favoriteAdd': 'Adicionar aos favoritos',
        'favoriteRemove': 'Remover dos favoritos',
        'homeDidYouKnow': 'Você sabia?',
        'homeOnThisDay': 'Neste dia',
        'newFanModeTitle': 'Modo iniciante',
        'newFanModeCta': 'Novo no futebol?',
        'compareTitle': 'Comparar times',
        'qualSimTitle': 'Simulador de classificação',
        'qualSimWin': 'Vitória',
        'qualSimDraw': 'Empate',
        'qualSimLose': 'Derrota',
        'offlinePackTitle': 'Pacote offline',
        'bracketTitle': 'Simulador de chaveamento',
        'bracketChampion': 'Campeão',
        'bracketRunnerUp': 'Vice',
        'formatGuideTitle': 'Guia do formato',
        'newsTitle': 'Notícias de futebol',
        'playerTitle': 'Jogador',
        'playerProfile': 'Perfil',
        'playerBiography': 'Biografia',
    },
    'ar': {  # Arabic — RTL handled by Flutter automatically
        '@@locale': 'ar',
        'appName': 'Football Fan Hub 2026',
        'navHome': 'الرئيسية',
        'navFixtures': 'المباريات',
        'navPredictor': 'التوقعات',
        'navTrivia': 'مسابقة',
        'navBracket': 'الجدول',
        'navStandings': 'الترتيب',
        'navFormat': 'النظام',
        'navNews': 'الأخبار',
        'actionSubmit': 'إرسال',
        'actionCancel': 'إلغاء',
        'actionShare': 'مشاركة',
        'actionSave': 'حفظ',
        'actionDone': 'تم',
        'actionRetry': 'إعادة',
        'actionRefresh': 'تحديث',
        'actionClose': 'إغلاق',
        'actionContinue': 'متابعة',
        'actionBack': 'رجوع',
        'actionClear': 'مسح',
        'actionDelete': 'حذف',
        'actionEdit': 'تعديل',
        'actionUpdate': 'تحديث',
        'actionPlay': 'تشغيل',
        'actionStart': 'ابدأ',
        'actionFinish': 'إنهاء',
        'actionViewAll': 'عرض الكل',
        'actionMore': 'المزيد',
        'statusLive': 'مباشر',
        'statusFinished': 'انتهت',
        'statusFullTime': 'نهاية المباراة',
        'statusHalfTime': 'نهاية الشوط',
        'statusUpcoming': 'القادمة',
        'statusScheduled': 'مجدولة',
        'statusToday': 'اليوم',
        'statusTomorrow': 'غدًا',
        'statusYesterday': 'أمس',
        'sectionTodayMatches': 'مباريات اليوم',
        'sectionFavoriteTeams': 'الفرق المفضلة',
        'sectionComingSoon': 'قريبًا',
        'sectionUpcomingMatches': 'المباريات القادمة',
        'sectionRecentForm': 'النتائج الأخيرة',
        'sectionStats': 'إحصائيات',
        'sectionSquad': 'التشكيلة',
        'sectionClubInfo': 'معلومات النادي',
        'sectionAbout': 'عن',
        'sectionGoals': 'الأهداف',
        'sectionMatchInfo': 'تفاصيل المباراة',
        'sectionLineups': 'التشكيلات',
        'sectionH2H': 'المواجهات',
        'sectionStandings': 'الترتيب',
        'sectionSubstitutes': 'البدلاء',
        'sectionStartingXI': 'التشكيلة الأساسية',
        'sectionBench': 'مقاعد البدلاء',
        'sectionAchievements': 'الإنجازات',
        'sectionStarPlayers': 'نجوم الفريق',
        'sectionCountryProfile': 'بيانات البلد',
        'sectionMomentum': 'الزخم',
        'sectionStatistics': 'الإحصائيات',
        'sectionTimeline': 'التوقيت',
        'sectionLiveTicker': 'متابعة مباشرة',
        'positionGoalkeepers': 'حراس المرمى',
        'positionDefenders': 'المدافعون',
        'positionMidfielders': 'لاعبو الوسط',
        'positionForwards': 'المهاجمون',
        'positionOther': 'آخرون',
        'tabSummary': 'الملخص',
        'tabLineups': 'التشكيلة',
        'tabStats': 'الإحصاء',
        'tabH2H': 'المواجهات',
        'tabStandings': 'الترتيب',
        'tabPitch': 'الملعب',
        'tabList': 'قائمة',
        'labelDate': 'التاريخ',
        'labelKickoff': 'بداية المباراة',
        'labelCompetition': 'البطولة',
        'labelStage': 'الدور',
        'labelGroup': 'المجموعة',
        'labelVenue': 'الملعب',
        'labelStatus': 'الحالة',
        'labelFounded': 'التأسيس',
        'labelManager': 'المدرب',
        'labelCoach': 'مدرب المنتخب',
        'labelCountry': 'البلد',
        'labelColours': 'الألوان',
        'labelWebsite': 'الموقع',
        'labelConfederation': 'الاتحاد',
        'labelPlayed': 'لُعبت',
        'labelWins': 'فوز',
        'labelDraws': 'تعادل',
        'labelLosses': 'خسارة',
        'labelGoalsFor': 'الأهداف له',
        'labelGoalsAgainst': 'الأهداف عليه',
        'labelGoalDiff': 'فرق الأهداف',
        'labelPoints': 'النقاط',
        'labelPosition': 'المركز',
        'labelNationality': 'الجنسية',
        'labelAge': 'العمر',
        'labelHeight': 'الطول',
        'labelWeight': 'الوزن',
        'labelShirt': 'القميص',
        'labelTeam': 'الفريق',
        'predictorTitle': 'التوقعات',
        'predictorYourPoints': 'نقاطك',
        'predictorSubmit': 'إرسال التوقع',
        'predictorBeatMe': 'هل يمكنك التفوق علي؟',
        'predictorShareIntro': 'توقعي',
        'triviaTitle': 'مسابقة كرة القدم اليومية',
        'triviaStart': 'بدء المسابقة',
        'triviaCorrect': 'صحيحة',
        'triviaStreak': 'متتالية',
        'triviaBest': 'الأفضل',
        'triviaToday': 'اليوم',
        'triviaPerfect': 'جولة مثالية!',
        'triviaGreatJob': 'عمل رائع!',
        'triviaFinalScore': 'النتيجة النهائية',
        'triviaQuit': 'إنهاء المسابقة؟',
        'triviaStay': 'البقاء',
        'triviaQuitAction': 'إنهاء',
        'stageGroup': 'دور المجموعات',
        'stageRoundOf32': 'دور الـ32',
        'stageRoundOf16': 'دور الـ16',
        'stageQuarterFinal': 'ربع النهائي',
        'stageSemiFinal': 'نصف النهائي',
        'stageFinal': 'النهائي',
        'stageThirdPlace': 'المركز الثالث',
        'settingsTitle': 'الإعدادات',
        'settingsLanguage': 'اللغة',
        'settingsDarkMode': 'الوضع الداكن',
        'settingsNotifications': 'الإشعارات',
        'settingsSupport': 'الدعم',
        'settingsFeedback': 'ملاحظات',
        'settingsRateUs': 'قيّمنا',
        'settingsShareApp': 'مشاركة التطبيق',
        'settingsRemoveAds': 'إزالة الإعلانات',
        'settingsAdsRemoved': 'تمت إزالة الإعلانات',
        'settingsAdsRemovedThanks': 'شكرًا لدعمك!',
        'settingsLanguageDialogTitle': 'اختر اللغة',
        'errorOffline': 'أنت غير متصل',
        'errorLoad': 'تعذر تحميل البيانات',
        'errorTryAgain': 'إعادة المحاولة',
        'errorNoMatches': 'لا توجد مباريات',
        'favoriteAdd': 'إضافة للمفضلة',
        'favoriteRemove': 'إزالة من المفضلة',
        'homeDidYouKnow': 'هل كنت تعلم؟',
        'homeOnThisDay': 'في مثل هذا اليوم',
        'newFanModeTitle': 'وضع المبتدئ',
        'newFanModeCta': 'جديد في كرة القدم؟',
        'compareTitle': 'مقارنة الفرق',
        'qualSimTitle': 'محاكي التأهل',
        'qualSimWin': 'فوز',
        'qualSimDraw': 'تعادل',
        'qualSimLose': 'خسارة',
        'offlinePackTitle': 'حزمة بدون إنترنت',
        'bracketTitle': 'محاكي الجدول',
        'bracketChampion': 'البطل',
        'bracketRunnerUp': 'الوصيف',
        'formatGuideTitle': 'دليل النظام',
        'newsTitle': 'أخبار كرة القدم',
        'playerTitle': 'اللاعب',
        'playerProfile': 'الملف الشخصي',
        'playerBiography': 'السيرة',
    },
}


def build():
    for locale, table in TRANSLATIONS.items():
        merged = {}
        # 1. Set the locale header FIRST so it can't be overwritten below.
        merged['@@locale'] = locale
        # 2. Walk all English keys, picking translation or English fallback.
        for key, en_val in en.items():
            if key == '@@locale':
                continue
            if key.startswith('@'):
                if key in metadata:
                    merged[key] = metadata[key]
                continue
            merged[key] = table.get(key, en_val)
        out_path = OUT_DIR / f'app_{locale}.arb'
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(merged, f, ensure_ascii=False, indent=2)
        n_keys = len([k for k in merged if not k.startswith('@')])
        print(f'wrote {out_path} (@@locale={merged["@@locale"]}, {n_keys} keys)')


if __name__ == '__main__':
    build()