// lib/core/services/daily_facts_service.dart
//
// Returns one fun football fact per calendar day. Deterministic by day-of-year
// so every user sees the same fact today.

class DailyFactsService {
  static String factForToday() => factFor(DateTime.now());

  static String factFor(DateTime date) {
    final dayOfYear = date.difference(DateTime(date.year, 1, 1)).inDays;
    return _facts[dayOfYear % _facts.length];
  }

  static const List<String> _facts = [
    'Brazil is the only nation to have played in every World Cup since 1930.',
    'Miroslav Klose has scored more World Cup goals (16) than anyone in history.',
    'The 2026 World Cup will be the first with 48 teams — an expansion from 32.',
    'The Maracanã in Rio held the unofficial world record attendance of 199,854 for the 1950 final.',
    'Cristiano Ronaldo is the first man to score in five different World Cups.',
    'Italy and Brazil are the only nations to win the World Cup four or more times each — though Italy holds 4 and Brazil 5.',
    'Lionel Messi has won 8 Ballon d\'Or awards, more than any other player.',
    'Pelé won three World Cups (1958, 1962, 1970) — a record no one else has matched.',
    'The fastest goal in World Cup history was scored by Hakan Şükür for Turkey vs South Korea in 2002, in just 10.8 seconds.',
    'Just Fontaine of France scored 13 goals in a single World Cup (1958) — still a record.',
    'Real Madrid have won the European Cup / Champions League more times than any other club (15+).',
    'The 1970 World Cup final (Brazil 4-1 Italy) is widely regarded as the greatest team performance ever.',
    'The original World Cup trophy, the Jules Rimet, was stolen twice — and never recovered after 1983.',
    'Maradona\'s "Goal of the Century" vs England in 1986 covered 60 metres and beat 5 defenders + the keeper.',
    'Argentina\'s Lionel Messi is the only player to win the Golden Ball at two World Cups (2014, 2022).',
    'England\'s only World Cup win came at home in 1966; Geoff Hurst remains the only player to score a hat-trick in a final.',
    'Germany 7-1 Brazil (2014 semi-final) was Brazil\'s worst-ever World Cup defeat and the largest semi-final win in history.',
    'The first World Cup was held in Uruguay in 1930, with only 13 invited teams.',
    'A football match is 90 minutes plus stoppage time, divided into two 45-minute halves.',
    'There are 11 players per side, and 5 substitutions are now allowed in most competitions.',
    'A yellow card is a caution; two in one match equals a red card and dismissal.',
    'The Premier League was founded in 1992, splitting from the English Football League.',
    'Bayern Munich have won the Bundesliga more often than any other club — dominating since the 1970s.',
    'PSG has won the most Ligue 1 titles since the 2010s, fuelled by Qatari investment.',
    'Spain became the first nation to win consecutive UEFA Euros (2008, 2012) bracketing a World Cup (2010).',
    'The "Hand of God" goal by Maradona in 1986 came just minutes before his "Goal of the Century" — same match!',
    'Brazilian striker Ronaldo Nazário scored a record 15 World Cup goals before Klose overtook him.',
    'The Copa América is the oldest international continental football competition (since 1916).',
    'CONMEBOL has 10 member nations — the smallest continental confederation in world football.',
    'African nations have reached the World Cup quarter-finals four times: Cameroon \'90, Senegal \'02, Ghana \'10, Morocco \'22.',
    'Morocco became the first African and first Arab nation to reach a World Cup semi-final in 2022.',
    'The "Bicycle Kick" was reportedly invented by Brazilian Leônidas in the 1930s — though several others claim it too.',
    'In 1994, Brazil won the World Cup on penalties, the first time a final was decided that way.',
    'Goalkeepers used to be allowed to pick up back-passes — the rule was changed in 1992 to stop time-wasting.',
    'A red card means the player must leave AND cannot be replaced — the team plays with 10 men.',
    'Football is the world\'s most popular sport, played by over 250 million people in 200+ countries.',
    'Liverpool FC plays at Anfield, one of the most atmospheric grounds in football. "You\'ll Never Walk Alone" is their anthem.',
    'Old Trafford in Manchester is nicknamed "The Theatre of Dreams" — chosen by Sir Bobby Charlton.',
    'The Camp Nou in Barcelona is the largest football stadium in Europe with ~99,000 capacity.',
    'Maracanã (Rio), Wembley (London), Camp Nou (Barcelona), Bernabéu (Madrid) and Old Trafford (Manchester) are five of football\'s most iconic stadiums.',
    'The North Korean Rungrado May Day Stadium has the largest official capacity in the world at 114,000.',
    'Total Football, the dominant tactical philosophy of the 1970s Netherlands, was created by Rinus Michels at Ajax.',
    'Tiki-Taka — Barcelona and Spain\'s short-passing dominance — was perfected by Pep Guardiola in the late 2000s.',
    'Catenaccio (Italian for "door bolt") was a defensive system that defined Italian football in the 1960s.',
    'Gegenpressing, used famously by Jürgen Klopp, focuses on winning the ball back within 5 seconds of losing it.',
    'A "false nine" plays as a striker but drops deep to draw out defenders — Messi excelled in this role.',
    'A "regista" is a deep-lying playmaker — Pirlo and Xabi Alonso were classics of the role.',
    'A "trequartista" plays between midfield and attack — Roberto Baggio and Zico were masters.',
    'A "libero" or sweeper was a defender who roamed freely; Franz Beckenbauer perfected the role.',
    'The 4-3-3 formation was popularised by the Dutch in the 1970s and is still widely used.',
    'A 4-2-3-1 is the most common modern Champions League formation.',
    'A "park-the-bus" tactic refers to extremely defensive setups with all players behind the ball.',
    'Penalties are taken from 12 yards (11 metres) from the goal line.',
    'The penalty spot was made the regulation distance in 1902 — before that, it was variable.',
    'A penalty shootout was first used at the World Cup in 1982 (semi-final between West Germany and France).',
    'Goalkeepers wear different-coloured kits to be clearly distinguishable from outfield players.',
    'In 1970, substitutions were finally allowed at the World Cup — only 2 per team per match.',
    'The Confederations Cup, last held in 2017, was discontinued from 2021.',
    'The UEFA Nations League, launched in 2018, was created to replace meaningless international friendlies.',
    'The Premier League sells global TV rights for over 5 billion dollar per cycle — the most valuable league.',
    'A draft pick system does NOT exist in football — clubs sign players via transfers and academies.',
    'A transfer window is a fixed period when clubs can buy and sell players; summer and January are the standard EU windows.',
    'A "Bosman ruling" (1995) gave players the right to leave clubs for free at the end of their contract.',
    'A "loan" sends a player to another club temporarily, often to gain experience or recover form.',
    'A "free agent" is a player out of contract who can sign for any club without a transfer fee.',
    'Carlos Tévez once played for both Manchester clubs, in their famous "Welcome to Manchester" billboard saga (2009).',
    'Sol Campbell shocked Arsenal fans by moving from Tottenham on a free in 2001 — the ultimate rivalry betrayal.',
    'Ole Gunnar Solskjær played 15 years at Manchester United, mostly as a super-sub, scoring crucial goals.',
    'Eric Cantona\'s kung-fu kick at a Crystal Palace fan in 1995 earned him a 9-month ban — but he came back to win more titles.',
    'Zinedine Zidane headbutted Marco Materazzi in his final match — the 2006 World Cup final.',
    'The longest match without a goal in major football was a 0-0 draw between Genoa and Lazio that lasted 480+ minutes across replays.',
    'The "Class of \'92" — Beckham, Giggs, Scholes, Butt, Neville brothers — won the FA Youth Cup before dominating United\'s senior team.',
    'Sir Alex Ferguson managed Manchester United for 26 years and won 13 Premier League titles.',
    'Arsène Wenger\'s Arsenal went unbeaten through the entire 2003-04 Premier League — the "Invincibles".',
    'Leicester City won the 2015-16 Premier League at 5000-1 odds — one of the greatest sports upsets ever.',
    'In 1998, Croatia (a 7-year-old nation) finished third at their first World Cup.',
    'Greece\'s shock EURO 2004 win is the only major Greek football trophy — they were 250-1 outsiders.',
    'Denmark won EURO 1992 having NOT qualified — they were a late replacement for Yugoslavia.',
    'Iceland (population ~360,000) reached the EURO 2016 quarter-finals — the smallest nation ever at a major tournament knockout.',
    'A "hat-trick" means 3 goals in one match by a single player.',
    'A "brace" means 2 goals in one match by a single player.',
    'A "screamer" is a powerful long-range goal.',
    'A "tap-in" is a goal scored from very close range, often after a deflection or rebound.',
    'A "nutmeg" is when a player passes the ball through an opponent\'s legs.',
    'A "rabona" kick wraps the kicking leg behind the standing leg — a flair move.',
    'A "scorpion kick" was made famous by René Higuita\'s goal-line save vs England in 1995.',
    'Cristiano Ronaldo\'s overhead bicycle kick vs Juventus in 2018 was so good that the Juve fans applauded him.',
    'A "panenka" is a chipped penalty straight down the middle — invented by Czech Antonín Panenka in 1976.',
    'A "Cruyff turn" is a 180-degree feint pioneered by Johan Cruyff at the 1974 World Cup.',
    'A "rainbow flick" arcs the ball over an opponent\'s head — Neymar uses it often.',
    'A "Maradona spin" is a 360-degree turn while shielding the ball — Maradona used it in the famous goal vs England.',
    'A "knuckleball" free kick wobbles unpredictably in the air — Cristiano Ronaldo perfected it.',
    'The longest single-club career in modern football was Francesco Totti\'s 25 years at Roma.',
    'Paolo Maldini played 25 years for AC Milan — never for another club.',
    'Ryan Giggs played all 24 years of his senior career at Manchester United.',
    'Lionel Messi scored 672 goals for Barcelona — the most goals for any single club.',
    'Cristiano Ronaldo is the all-time top scorer in men\'s international football with 130+ goals.',
    'A "golden generation" describes an unusually talented group of national-team players from one era.',
    'Sócrates, the Brazilian midfielder, was a qualified doctor and democracy activist as well as a football genius.',
    'Diego Maradona once played in Italian Serie B for Napoli, lifting them to two Scudetti (\'87, \'90).',
    'Bobby Moore is the only England player to lift the World Cup trophy (1966) — he was the captain.',
    'Gerd Müller scored more goals per game (0.85) than any other Bayern Munich great.',
    'Marco van Basten\'s volley in the EURO 1988 final vs USSR is widely called the greatest goal in tournament history.',
    'Andrés Iniesta scored Spain\'s only goal in the 2010 World Cup final to beat Netherlands.',
    'Mario Götze scored Germany\'s winning goal vs Argentina in the 2014 World Cup final.',
    'Lionel Messi scored 7 goals across the 2022 World Cup, including 2 in the final.',
    'Kylian Mbappé became the first man since Pelé to score a hat-trick in a World Cup final (2022).',
    'Bobby Charlton was Manchester United\'s top scorer for over 50 years until Wayne Rooney passed him in 2017.',
    'A football weighs between 410 and 450 grams (14 to 16 ounces).',
    'A football pitch must be between 100 and 110 metres long and 64 to 75 metres wide.',
    'The corner arc has a radius of 1 metre.',
    'The penalty spot is 11 metres (12 yards) from the goal line.',
    'A goal in football is 7.32 metres wide and 2.44 metres high (8 yards by 8 feet).',
  ];
}
